-----------------------------------------------------------------------------------
-- US3464590                                                                     --
-- Application: BW Wholesale                                                     --
-- Area: Customer                                                                --
-- Sub-Area: Banking information & Wholesale Products                            --
-----------------------------------------------------------------------------------

EXEC sp_set_session_context N'CHNG_REQT_NB', N'US3464590'
GO

USE ${DBNAME}
GO


---------------------------------------------------------------------------------
-- Banking tables
---------------------------------------------------------------------------------
CREATE TABLE dbo.ZBWT108_BANK
-- FOR SYSTEM NAME ZBWT108
( 
BANK_ID_NB           /*-- FOR COLUMN IDBANK --*/ nchar(36)  NOT NULL ,
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
BANK_CD              /*-- FOR COLUMN CDBANK --*/ nchar(5)  NOT NULL ,
BANK_NM              /*-- FOR COLUMN TXBANK --*/ nvarchar(250)  NOT NULL ,
BIC_CD               /*-- FOR COLUMN CDBIC --*/ nchar(11)  NOT NULL ,
STAT_CD              /*-- FOR COLUMN CDSTATUS --*/ nchar(1)  NOT NULL ,
STAT_TS              /*-- FOR COLUMN TSSTATUS --*/ datetime  NOT NULL ,
STAT_USER_ID_CD      /*-- FOR COLUMN CDSTATUSER --*/ nchar(9)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT108_BANK
ADD CONSTRAINT ZBWT1081 PRIMARY KEY  CLUSTERED (BANK_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1082 ON dbo.ZBWT108_BANK
( 
ISO_CNTRY_CD          ASC,
BANK_CD               ASC
)
go


CREATE TABLE dbo.ZBWT109_BANK_BR
-- FOR SYSTEM NAME ZBWT109
( 
BANK_BR_ID_NB        /*-- FOR COLUMN IDBANKBR --*/ nchar(36)  NOT NULL ,
BANK_BR_CD           /*-- FOR COLUMN CDBNKBRCH --*/ nchar(5)  NOT NULL ,
BANK_ID_NB           /*-- FOR COLUMN IDBANK --*/ nchar(36)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT109_BANK_BR
ADD CONSTRAINT ZBWT1091 PRIMARY KEY  CLUSTERED (BANK_BR_ID_NB ASC)
go

ALTER TABLE dbo.ZBWT110_CUST_BANK_ACCT
ADD CONSTRAINT ZBWT1101 PRIMARY KEY  CLUSTERED (CUST_BANK_ACCT_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1102 ON dbo.ZBWT110_CUST_BANK_ACCT
( 
CUST_ID_NB            ASC,
DD_BANK_CD            ASC
)
go


CREATE TABLE dbo.ZBWT110_CUST_BANK_ACCT
-- FOR SYSTEM NAME ZBWT110
( 
CUST_BANK_ACCT_ID_NB /*-- FOR COLUMN IDCUSTBNK --*/ nchar(36)  NOT NULL ,
CUST_ID_NB           /*-- FOR COLUMN IDCUST --*/ nchar(36)  NOT NULL ,
DD_BANK_CD           /*-- FOR COLUMN PVBNKUSE --*/ nchar(2)  NOT NULL ,
BANK_ID_NB           /*-- FOR COLUMN IDBANK --*/ nchar(36)  NOT NULL ,
BANK_BR_ID_NB        /*-- FOR COLUMN IDBANKBR --*/ nchar(36)  NULL ,
CUST_BANK_ACCT_NB    /*-- FOR COLUMN TXBANKACC --*/ nchar(40)  NULL ,
CUST_BANK_ACCT_DSPLY_IN /*-- FOR COLUMN INACCNTEW --*/ nchar(1)  NOT NULL 
CONSTRAINT ZBWT110_CUST_BANK_ACCT_DSPLY_IN_DFT DEFAULT  N'N',
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT110_CUST_BANK_ACCT
ADD CONSTRAINT ZBWT1101 PRIMARY KEY  CLUSTERED (CUST_BANK_ACCT_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1102 ON dbo.ZBWT110_CUST_BANK_ACCT
( 
CUST_ID_NB            ASC,
DD_BANK_CD            ASC
)
go


CREATE TABLE dbo.ZBWT111_MNDT
-- FOR SYSTEM NAME ZBWT111
( 
MNDT_ID_NB           /*-- FOR COLUMN IDMNDT --*/ nchar(36)  NOT NULL ,
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NOT NULL ,
MNDT_REFNC_CD        /*-- FOR COLUMN NMMNDRF --*/ nchar(21)  NOT NULL ,
CUST_BANK_ACCT_ID_NB /*-- FOR COLUMN IDCUSTBNK --*/ nchar(36)  NOT NULL ,
CUST_ID_NB           /*-- FOR COLUMN IDCUST --*/ nchar(36)  NOT NULL ,
STAT_CD              /*-- FOR COLUMN CDSTATUS --*/ nchar(1)  NOT NULL ,
STAT_TS              /*-- FOR COLUMN TSSTATUS --*/ datetime  NOT NULL ,
STAT_USER_ID_CD      /*-- FOR COLUMN CDSTATUSER --*/ nchar(9)  NOT NULL ,
MNDT_SQNC_NB         /*-- FOR COLUMN CDSQNM --*/ smallint  NOT NULL ,
MNDT_DESC_TX         /*-- FOR COLUMN TXMANDATE --*/ nvarchar(250)  NOT NULL ,
SEPA_DD_TYPE_CD      /*-- FOR COLUMN TPMANDATE --*/ nvarchar(4)  NOT NULL ,
MNDT_EFF_DT          /*-- FOR COLUMN DTMANDATE --*/ date  NOT NULL ,
MNDT_SIGN_CITY_NM    /*-- FOR COLUMN CTSIGNTRE --*/ nvarchar(250)  NOT NULL ,
PAYER_NM             /*-- FOR COLUMN SNPAYER --*/ nvarchar(250)  NOT NULL ,
PAYER_NTNL_ID_NB     /*-- FOR COLUMN IDPAYER --*/ nvarchar(100)  NOT NULL ,
PAYER_POST_ADDR_ID_NB /*-- FOR COLUMN IDPYRPOADD --*/ nchar(36)  NOT NULL ,
CRDTR_NM             /*-- FOR COLUMN SNCREDTR --*/ nvarchar(250)  NOT NULL ,
SEPA_CRDTR_ID_NB     /*-- FOR COLUMN IDCREDTR --*/ nchar(35)  NOT NULL ,
CRDTR_POST_ADDR_ID_NB /*-- FOR COLUMN IDCRDPOADD --*/ nchar(36)  NOT NULL ,
CNTRCT_REFNC_NB      /*-- FOR COLUMN CDCREDTR --*/ nchar(5)  NOT NULL ,
CNTRCT_REFNC_TX      /*-- FOR COLUMN TXCREDTR --*/ nvarchar(250)  NOT NULL ,
MNDT_STAT_CD         /*-- FOR COLUMN STMANDATE --*/ nchar(1)  NOT NULL ,
MNDT_STAT_DT         /*-- FOR COLUMN DTSTATUS --*/ date  NOT NULL ,
CMT_TX               /*-- FOR COLUMN TXCOM --*/ nvarchar(500)  NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT1111 PRIMARY KEY  CLUSTERED (MNDT_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1112 ON dbo.ZBWT111_MNDT
( 
ISO_CNTRY_CD          ASC,
WHSL_FIN_LABEL_CD     ASC,
MNDT_REFNC_CD         ASC
)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1113 ON dbo.ZBWT111_MNDT
( 
CUST_BANK_ACCT_ID_NB  ASC
)
go


CREATE TABLE dbo.ZBWT112_FC_BANK_ACCT
-- FOR SYSTEM NAME ZBWT112
( 
FC_BANK_ACCT_ID_NB   /*-- FOR COLUMN IDFCBNKACC --*/ nchar(36)  NOT NULL ,
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NOT NULL ,
BANK_ID_NB           /*-- FOR COLUMN IDBANK --*/ nchar(36)  NOT NULL ,
WFL_BANK_ACCT_NB     /*-- FOR COLUMN CDBNKACCNT --*/ nchar(40)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT112_FC_BANK_ACCT
ADD CONSTRAINT ZBWT1121 PRIMARY KEY  CLUSTERED (FC_BANK_ACCT_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1122 ON dbo.ZBWT112_FC_BANK_ACCT
( 
ISO_CNTRY_CD          ASC,
WHSL_FIN_LABEL_CD     ASC,
BANK_ID_NB            ASC,
WFL_BANK_ACCT_NB      ASC
)
go

---------------------------------------------------------------------------------
-- Customer Basic Information tables
---------------------------------------------------------------------------------
ALTER TABLE dbo.ZBWT101_CUST
ADD DD_IN                /*-- FOR COLUMN INDD --*/ nchar(1)  NULL 
go 

ALTER TABLE dbo.ZBWT101_CUST
ADD CPTL_DD_IN           /*-- FOR COLUMN INUSECAPDD --*/ nchar(1)  NULL
go

ALTER TABLE dbo.ZBWT101_CUST
ADD INT_DD_IN            /*-- FOR COLUMN INUSEINTDD --*/ nchar(1)  NULL
go

ALTER TABLE dbo.ZBWT101_CUST
ADD SMALL_BAL_DD_FUNC_IN /*-- FOR COLUMN INSMLBAL --*/ nchar(1)  NULL 
go


ALTER TABLE dbo.ZBWT821_CNTRY
ADD SEPA_IN              /*-- FOR COLUMN INSEPA --*/ nchar(1)  NULL 
go

---------------------------------------------------------------------------------
-- Finance Products tables
---------------------------------------------------------------------------------
CREATE TABLE dbo.ZBWT113_CUST_BT
-- FOR SYSTEM NAME ZBWT113
( 
CUST_BT_ID_NB        /*-- FOR COLUMN IDCUSTBT --*/ nchar(36)  NOT NULL ,
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NOT NULL ,
CUST_ID_NB           /*-- FOR COLUMN IDCUST --*/ nchar(36)  NOT NULL ,
WHSL_BUS_TYPE_CD     /*-- FOR COLUMN CDBUSTYPE --*/ nchar(2)  NOT NULL ,
STAT_CD              /*-- FOR COLUMN CDSTATUS --*/ nchar(1)  NOT NULL ,
STAT_TS              /*-- FOR COLUMN TSSTATUS --*/ datetime  NOT NULL ,
STAT_USER_ID_CD      /*-- FOR COLUMN CDSTATUSER --*/ nchar(9)  NOT NULL ,
FIN_HOLD_IN          /*-- FOR COLUMN INFINANHLD --*/ nchar(1)  NOT NULL ,
CVWA_IN              /*-- FOR COLUMN INCVWA --*/ nchar(1)  NOT NULL ,
UV_DFLT_WHSL_BT_IN   /*-- FOR COLUMN INBTUVDFT --*/ nchar(1)  NOT NULL ,
BLW_DPP_ACTP_IN      /*-- FOR COLUMN INAUTACDPP --*/ nchar(1)  NOT NULL ,
BLW_IDT_ACPT_IN      /*-- FOR COLUMN INAUTACPTI --*/ nchar(1)  NOT NULL ,
BLW_PAY_ACTP_IN      /*-- FOR COLUMN INAUTACPTP --*/ nchar(1)  NOT NULL ,
BLW_PLNX_ACPT_IN     /*-- FOR COLUMN INAUTACPTX --*/ nchar(1)  NOT NULL ,
BLW_RFN_ACTP_IN      /*-- FOR COLUMN INAUTACPTR --*/ nchar(1)  NOT NULL ,
BLW_TDC_ACTP_IN      /*-- FOR COLUMN INAUTACPTT --*/ nchar(1)  NOT NULL ,
BLW_VEH_ACTP_IN      /*-- FOR COLUMN INAUTACPTV --*/ nchar(1)  NOT NULL ,
STLMT_DAY_CT         /*-- FOR COLUMN DASETTLMNT --*/ numeric(2)  NULL ,
FC_BANK_ACCT_ID_NB   /*-- FOR COLUMN IDFCBNKACC --*/ nchar(36)  NULL ,
INT_CUST_BNK_ID_NB   /*-- FOR COLUMN IDCUSTBNK --*/ nchar(36)  NULL ,
CUST_WHSL_BUS_TYPE_TRMNT_DT /*-- FOR COLUMN DTDLRTRM --*/ date  NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT113_CUST_BT
ADD CONSTRAINT ZBWT1131 PRIMARY KEY  CLUSTERED (CUST_BT_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1132 ON dbo.ZBWT113_CUST_BT
( 
ISO_CNTRY_CD          ASC,
WHSL_FIN_LABEL_CD     ASC,
CUST_ID_NB            ASC,
WHSL_BUS_TYPE_CD      ASC
)
go


CREATE TABLE dbo.ZBWT114_CUST_BT_PLN
-- FOR SYSTEM NAME ZBWT114
( 
CUST_BT_FIN_PLN_ID_NB /*-- FOR COLUMN IDCUSTBTPL --*/ nchar(36)  NOT NULL ,
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NULL ,
CUST_BT_ID_NB        /*-- FOR COLUMN IDCUSTBT --*/ nchar(36)  NOT NULL ,
WHSL_BUS_TYPE_CD     /*-- FOR COLUMN CDBUSTYPE --*/ nchar(2)  NULL ,
FIN_PLN_CD           /*-- FOR COLUMN CDPLAN --*/ nchar(2)  NOT NULL ,
FIN_PLN_DEFLT_IN     /*-- FOR COLUMN INDEFPLNEW --*/ nchar(1)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWT114_CUST_BT_PLN
ADD CONSTRAINT ZBWT1141 PRIMARY KEY  CLUSTERED (CUST_BT_FIN_PLN_ID_NB ASC)
go

CREATE UNIQUE NONCLUSTERED INDEX ZBWT1142 ON dbo.ZBWT114_CUST_BT_PLN
( 
ISO_CNTRY_CD          ASC,
WHSL_FIN_LABEL_CD     ASC,
CUST_BT_ID_NB         ASC,
WHSL_BUS_TYPE_CD      ASC,
FIN_PLN_CD            ASC
)
go


---------------------------------------------------------------------------------
-- Data Projected tables (from Wholesale Products) 
---------------------------------------------------------------------------------
CREATE TABLE dbo.ZBWTxx0_T130_BUS_TYPE
-- FOR SYSTEM NAME ZBWTxx0
( 
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NOT NULL ,
WHSL_BUS_TYPE_CD     /*-- FOR COLUMN CDBUSTYPE --*/ nchar(2)  NOT NULL ,
WHSL_BUS_TYPE_DS     /*-- FOR COLUMN TXBUSTYPE --*/ nvarchar(250)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWTxx0_T130_BUS_TYPE
ADD CONSTRAINT ZBWTxx01 PRIMARY KEY  CLUSTERED (ISO_CNTRY_CD ASC,WHSL_FIN_LABEL_CD ASC,WHSL_BUS_TYPE_CD ASC)
go


CREATE TABLE dbo.ZBWTxx1_T131_FIN_PLAN
-- FOR SYSTEM NAME ZBWTxx1
( 
ISO_CNTRY_CD         /*-- FOR COLUMN CDISOLOC --*/ nchar(2)  NOT NULL ,
WHSL_FIN_LABEL_CD    /*-- FOR COLUMN CDCOMPANY --*/ smallint  NOT NULL ,
WHSL_BUS_TYPE_CD     /*-- FOR COLUMN CDBUSTYPE --*/ nchar(2)  NOT NULL ,
FIN_PLN_CD           /*-- FOR COLUMN CDPLAN --*/ nchar(2)  NOT NULL ,
FIN_PLN_NM           /*-- FOR COLUMN TXPLAN --*/ nvarchar(250)  NOT NULL ,
CRT_TS               /*-- FOR COLUMN TSCREATE --*/ datetime  NOT NULL ,
CRT_USER_ID_CD       /*-- FOR COLUMN SNCREATE --*/ nvarchar(128)  NOT NULL ,
LSTUPDT_TS           /*-- FOR COLUMN TSLSTUPD --*/ datetime  NOT NULL ,
LSTUPDT_USER_ID_CD   /*-- FOR COLUMN SNLSTUPD --*/ nvarchar(128)  NOT NULL 
)
go

ALTER TABLE dbo.ZBWTxx1_T131_FIN_PLAN
ADD CONSTRAINT ZBWTxx11 PRIMARY KEY  CLUSTERED (ISO_CNTRY_CD ASC,WHSL_FIN_LABEL_CD ASC,WHSL_BUS_TYPE_CD ASC,FIN_PLN_CD ASC)
go


---------------------------------------------------------------------------------
-- Banking FKs
---------------------------------------------------------------------------------
ALTER TABLE dbo.ZBWT108_BANK
ADD CONSTRAINT ZBWT821_ZBWT108 FOREIGN KEY (ISO_CNTRY_CD) REFERENCES dbo.ZBWT821_CNTRY(ISO_CNTRY_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT108_BANK
ADD CONSTRAINT ZBWT825_ZBWT108 FOREIGN KEY (STAT_CD) REFERENCES dbo.ZBWT825_STATUS(STAT_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go


ALTER TABLE dbo.ZBWT109_BANK_BR
ADD CONSTRAINT ZBWT108_ZBWT109 FOREIGN KEY (BANK_ID_NB) REFERENCES dbo.ZBWT108_BANK(BANK_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go


ALTER TABLE dbo.ZBWT110_CUST_BANK_ACCT
ADD CONSTRAINT ZBWT101_ZBWT108 FOREIGN KEY (CUST_ID_NB) REFERENCES dbo.ZBWT101_CUST(CUST_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT110_CUST_BANK_ACCT
ADD CONSTRAINT ZBWT108_ZBWT110 FOREIGN KEY (BANK_ID_NB) REFERENCES dbo.ZBWT108_BANK(BANK_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT110_CUST_BANK_ACCT
ADD CONSTRAINT ZBWT109_ZBWT110 FOREIGN KEY (BANK_BR_ID_NB) REFERENCES dbo.ZBWT109_BANK_BR(BANK_BR_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT110_ZBWT111 FOREIGN KEY (CUST_BANK_ACCT_ID_NB) REFERENCES dbo.ZBWT110_CUST_BANK_ACCT(CUST_BANK_ACCT_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT822_ZBWT111 FOREIGN KEY (ISO_CNTRY_CD,WHSL_FIN_LABEL_CD) REFERENCES dbo.ZBWT822_WHSL_FIN_CO(ISO_CNTRY_CD,WHSL_FIN_LABEL_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT825_ZBWT111 FOREIGN KEY (STAT_CD) REFERENCES dbo.ZBWT825_STATUS(STAT_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT107_ZBWT111 FOREIGN KEY (PAYER_POST_ADDR_ID_NB) REFERENCES dbo.ZBWT107_POST_ADDR(POST_ADDR_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT107_ZBWT111_2 FOREIGN KEY (CRDTR_POST_ADDR_ID_NB) REFERENCES dbo.ZBWT107_POST_ADDR(POST_ADDR_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT111_MNDT
ADD CONSTRAINT ZBWT101_ZBWT111 FOREIGN KEY (CUST_ID_NB) REFERENCES dbo.ZBWT101_CUST(CUST_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT112_FC_BANK_ACCT
ADD CONSTRAINT ZBWT822_ZBWT112 FOREIGN KEY (ISO_CNTRY_CD,WHSL_FIN_LABEL_CD) REFERENCES dbo.ZBWT822_WHSL_FIN_CO(ISO_CNTRY_CD,WHSL_FIN_LABEL_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT112_FC_BANK_ACCT
ADD CONSTRAINT ZBWT108_ZBWT112 FOREIGN KEY (BANK_ID_NB) REFERENCES dbo.ZBWT108_BANK(BANK_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

---------------------------------------------------------------------------------
-- Finance Products FKs
---------------------------------------------------------------------------------
ALTER TABLE dbo.ZBWT113_CUST_BT
ADD CONSTRAINT ZBWT101_ZBWT113 FOREIGN KEY (CUST_ID_NB) REFERENCES dbo.ZBWT101_CUST(CUST_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT113_CUST_BT
ADD CONSTRAINT ZBWT110_ZBWT1132 FOREIGN KEY (INT_CUST_BNK_ID_NB) REFERENCES dbo.ZBWT110_CUST_BANK_ACCT(CUST_BANK_ACCT_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT113_CUST_BT
ADD CONSTRAINT ZBWT825_ZBWT113 FOREIGN KEY (STAT_CD) REFERENCES dbo.ZBWT825_STATUS(STAT_CD)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT113_CUST_BT
ADD CONSTRAINT ZBWT112_ZBWT113 FOREIGN KEY (FC_BANK_ACCT_ID_NB) REFERENCES dbo.ZBWT112_FC_BANK_ACCT(FC_BANK_ACCT_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

ALTER TABLE dbo.ZBWT114_CUST_BT_PLN
ADD CONSTRAINT ZBWT113_ZBWT114 FOREIGN KEY (CUST_BT_ID_NB) REFERENCES dbo.ZBWT113_CUST_BT(CUST_BT_ID_NB)
ON DELETE NO ACTION
ON UPDATE NO ACTION
go

